name: Build and push docker images
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Comment"
  push:
    branches: [main, master]
    paths:
      - "app.json"
      - ".github/workflows/docker.yml"
env:
  IMAGE_ORG: yaoapp
  IMAGE_NAME: ${{ github.event.repository.name }}
  REPO_DOCKERFILES: ${{ github.repository_owner }}/dockerfiles
  VERSION: 1.0.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles
        uses: actions/checkout@v2
        with:
          repository: ${{ env.REPO_DOCKERFILES }}
          path: dockerfiles

      - name: Move Dockerfiles
        run: |
          mv dockerfiles ../
          ls -l .
          ls -l ../

      - name: Checkout Application Source
        uses: actions/checkout@v2

      - name: Get Version
        run: |
          VERSION=$(cat app.json |grep version |awk -F : '{print $2}' | sed 's/"//g' | sed 's/,//g' | sed 's/ //g')
          if [ -z "$VERSION" ]; then 
            VERSION=1.0.0
          fi
          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Check Version
        run: echo $VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image AMD64
        uses: docker/build-push-action@v2
        with:
          context: ../dockerfiles/application/amd64
          platforms: linux/amd64
          build-args: |
            VERSION=${{ env.VERSION }}
            REPO=github.com/${{ github.repository }}
            TOKEN=${{ secrets.GITHUB_TOKEN	}}
          push: true
          tags: ${{ env.IMAGE_ORG }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-amd64

      - name: Build & Push Docker Image ARM64
        uses: docker/build-push-action@v2
        with:
          context: ../dockerfiles/application/arm64
          platforms: linux/arm64
          build-args: |
            VERSION=${{ env.VERSION }}
            REPO=github.com/${{ github.repository }}
            TOKEN=${{ secrets.GITHUB_TOKEN	}}
          push: true
          tags: ${{ env.IMAGE_ORG }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-arm64
